# Generated by Django 5.1 on 2024-11-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_feedback_options_alter_subscription_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="subject",
            field=models.CharField(
                choices=[
                    ("question", "Вопрос"),
                    ("suggestion", "Предложение"),
                    ("complaint", "Жалоба"),
                ],
                default="question",
                max_length=200,
                verbose_name="Тема",
            ),
        ),
    ]
