# Generated by Django 5.1 on 2024-12-06 16:58

import common.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[
                    ("unemployed", "Не ищу работу"),
                    ("search", "В поиске работы"),
                ],
                default="search",
                max_length=300,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="employee/employee.jpg",
                null=True,
                upload_to=common.service.get_path_for_avatar_resume,
                verbose_name="Аватар",
            ),
        ),
    ]
