# Generated by Django 5.1 on 2024-11-21 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employee_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLinkEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("vk", "Вконтакте"),
                            ("linkedin", "LinkedIn"),
                            ("tg", "Telegram"),
                            ("github", "GitHub"),
                            ("gitlab", "GitLab"),
                            ("habr", "Habr"),
                            ("other", "Другое"),
                        ],
                        max_length=300,
                        verbose_name="Название",
                    ),
                ),
                ("link", models.URLField(blank=True, null=True, verbose_name="Ссылка")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                        verbose_name="Работник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Социальная сеть",
                "verbose_name_plural": "Социальные сети",
            },
        ),
    ]
