# Generated by Django 5.1 on 2024-11-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_employee_stacks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="experience",
        ),
    ]
