# Generated by Django 5.1 on 2024-11-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_employee_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Мужской"),
                    ("female", "Женский"),
                    ("other", "Не указано"),
                ],
                default="other",
                max_length=255,
                verbose_name="Пол",
            ),
        ),
    ]
