# Generated by Django 5.1 on 2024-11-25 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0009_remove_employee_middle_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="employees.employee",
                verbose_name="Работник",
            ),
        ),
    ]
