# Generated by Django 5.1 on 2024-11-25 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0010_alter_project_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resumes",
                to="employees.employee",
                verbose_name="Работник",
            ),
        ),
    ]
