# Generated by Django 5.1 on 2024-11-25 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0011_alter_resume_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiences",
                to="employees.employee",
                verbose_name="Работник",
            ),
        ),
    ]
