# Generated by Django 5.1 on 2024-11-25 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0012_alter_experience_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("university", "Высшее образование"),
                            ("course", "Курсы"),
                        ],
                        default="university",
                        max_length=300,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "university",
                    models.CharField(max_length=300, verbose_name="Университет"),
                ),
                (
                    "specialization",
                    models.CharField(max_length=300, verbose_name="Специализация"),
                ),
                ("start_date", models.DateField(verbose_name="Начало обучения")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Окончание обучения"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                        verbose_name="Работник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Образование",
                "verbose_name_plural": "Образование",
            },
        ),
    ]
