# Generated by Django 5.1 on 2024-11-25 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0013_education"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educations",
                to="employees.employee",
                verbose_name="Работник",
            ),
        ),
    ]
