# Generated by Django 5.1 on 2024-11-25 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0015_commentproject"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentproject",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employees.commentproject",
                verbose_name="Родительский комментарий",
            ),
        ),
    ]
