# Generated by Django 5.1 on 2024-11-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0017_project_dislikes_alter_project_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Отчество"
            ),
        ),
    ]
