# Generated by Django 5.1 on 2024-11-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0019_alter_commentproject_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="min_salary",
            field=models.SmallIntegerField(
                null=True, verbose_name="Минимальная зарплата"
            ),
        ),
    ]
