# Generated by Django 5.1 on 2024-11-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0020_alter_resume_min_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="currency",
            field=models.CharField(
                choices=[("RUB", "RUB"), ("USD", "USD"), ("EUR", "EUR")],
                default="RUB",
                max_length=200,
                verbose_name="Валюта",
            ),
        ),
    ]
