# Generated by Django 5.1 on 2024-12-01 17:24

import common.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0021_resume_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="employees/default.png",
                null=True,
                upload_to=common.service.get_path_for_avatar,
                verbose_name="Аватар",
            ),
        ),
    ]
