# Generated by Django 5.1 on 2024-11-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "Работник", "verbose_name_plural": "Работники"},
        ),
        migrations.AlterField(
            model_name="company",
            name="slug",
            field=models.SlugField(
                blank=True, null=True, unique=True, verbose_name="Слаг"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="slug",
            field=models.SlugField(
                blank=True, null=True, unique=True, verbose_name="Слаг"
            ),
        ),
    ]
