# Generated by Django 5.1 on 2024-11-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_resume_employee_alter_vacancy_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="status_vacancy",
            field=models.CharField(
                choices=[("open", " Открыта"), ("archived", "Архив")],
                default="open",
                max_length=200,
                verbose_name="Статус вакансии",
            ),
        ),
    ]
