# Generated by Django 5.1 on 2024-11-09 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_vacancy_status_vacancy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="requirements",
            field=models.TextField(
                default="", max_length=3000, verbose_name="Требования"
            ),
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=300, verbose_name="Компания")),
                (
                    "position",
                    models.CharField(max_length=200, verbose_name="Должность"),
                ),
                (
                    "requirements",
                    models.TextField(max_length=3000, verbose_name="Требования"),
                ),
                ("start_date", models.DateField(verbose_name="Начало работы")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Окончание работы"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Профиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опыт работы",
                "verbose_name_plural": "Опыт работы",
            },
        ),
        migrations.AddField(
            model_name="resume",
            name="experience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.experience",
                verbose_name="Опыт работы",
            ),
        ),
    ]
