# Generated by Django 5.1 on 2024-11-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_resume_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="stacks",
            field=models.ManyToManyField(
                blank=True, to="core.stack", verbose_name="Стек"
            ),
        ),
    ]
