# Generated by Django 5.1 on 2024-11-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_vacancy_stacks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="experience",
            field=models.ManyToManyField(
                blank=True, to="core.experience", verbose_name="Опыт работы"
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="stacks",
            field=models.ManyToManyField(
                blank=True, to="core.stack", verbose_name="Стек"
            ),
        ),
    ]
