# Generated by Django 5.1 on 2024-11-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_category_options_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, null=True, unique=True, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "verbose_name": " Стек",
                "verbose_name_plural": "Стеки",
            },
        ),
    ]
