# Generated by Django 5.1 on 2024-11-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="visibility",
            field=models.BooleanField(default=True, verbose_name="Видимость"),
        ),
    ]
