# Generated by Django 5.1 on 2024-11-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_experience_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="work_schedule",
            field=models.CharField(
                choices=[
                    ("full-time", "Полный рабочий день"),
                    ("part-time", "Частичная занятость"),
                    ("remote", "Удаленная работа"),
                ],
                default="full-time",
                max_length=200,
                verbose_name="График работы",
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="work_schedule",
            field=models.CharField(
                choices=[
                    ("full-time", "Полный рабочий день"),
                    ("part-time", "Частичная занятость"),
                    ("remote", "Удаленная работа"),
                ],
                default="full-time",
                max_length=200,
                verbose_name="График работы",
            ),
        ),
    ]
