# Generated by Django 5.1 on 2024-11-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_resume_work_schedule_vacancy_work_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="about",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="requirements",
            field=models.TextField(
                blank=True, max_length=3000, null=True, verbose_name="Требования"
            ),
        ),
    ]
