# Generated by Django 5.1 on 2024-11-14 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_vacancy_about"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="about",
            field=models.TextField(
                blank=True, max_length=3500, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Работник",
            ),
        ),
    ]
