# Generated by Django 5.1 on 2024-11-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_experience_about_alter_experience_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="stacks",
            field=models.ManyToManyField(to="core.stack", verbose_name="Стек"),
        ),
    ]
