# Generated by Django 5.1 on 2024-11-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_experience_stacks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="requirements",
            field=models.TextField(
                blank=True, max_length=3000, null=True, verbose_name="Требования"
            ),
        ),
    ]
