# Generated by Django 5.1 on 2024-11-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_experience_requirements"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="experience",
        ),
        migrations.AddField(
            model_name="resume",
            name="experience",
            field=models.ManyToManyField(
                to="core.experience", verbose_name="Опыт работы"
            ),
        ),
    ]
