# Generated by Django 5.1 on 2024-11-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_favoriteresume_favoritevacancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="level",
            field=models.CharField(
                choices=[
                    ("intern", "Intern"),
                    ("junior", "Junior"),
                    ("junior_plus", "Junior+"),
                    ("middle", "Middle"),
                    ("middle_plus", "Middle+"),
                    ("senior", "Senior"),
                    ("team_lead", "Team Lead"),
                ],
                default="junior",
                max_length=200,
                verbose_name="Уровень",
            ),
        ),
    ]
