# Generated by Django 5.1 on 2024-11-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="online",
            field=models.BooleanField(default=False, verbose_name="онлайн"),
        ),
    ]
