# Generated by Django 5.1 on 2024-12-09 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="friend_request",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="accounts.friendrequest",
                verbose_name="Заявка в друзья",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Отправлена"),
                    ("accepted", "Принята"),
                    ("rejected", "Отклонена"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
    ]
