# Generated by Django 5.1 on 2024-11-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="verified",
            new_name="is_verified",
        ),
    ]
