# Generated by Django 5.1 on 2024-11-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_online"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="verified",
            field=models.BooleanField(default=False, verbose_name="Проверенный"),
        ),
    ]
