# Generated by Django 5.1 on 2024-11-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_verified_user_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[("Company", "Компания"), ("Employee", "Работник")],
                default="Employee",
                max_length=255,
                verbose_name="Тип",
            ),
        ),
    ]
