# Generated by Django 5.1 on 2024-12-09 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_message_friend_request_message_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="status",
        ),
    ]
