# Generated by Django 5.1 on 2024-12-09 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_message_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="to_user",
            new_name="receiver",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="from_user",
            new_name="sender",
        ),
    ]
