# Generated by Django 5.1 on 2024-11-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="link",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Ссылка на сайт"
            ),
        ),
    ]
