# Generated by Django 5.1 on 2024-11-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_friendrequest_options_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("Company", "Компания"),
                    ("Employee", "Работник"),
                    ("Admin", "Администратор"),
                ],
                default="Employee",
                max_length=255,
                verbose_name="Тип",
            ),
        ),
    ]
