# Generated by Django 5.1 on 2024-11-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_company_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="count_employees",
            field=models.SmallIntegerField(
                default=0, verbose_name="Количество  сотрудников"
            ),
        ),
    ]
