# Generated by Django 5.1 on 2024-11-24 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_company_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="count_employees",
            field=models.SmallIntegerField(
                default=0, verbose_name="Количество  сотрудников"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="stars",
            field=models.SmallIntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Оценка",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="level",
            field=models.CharField(
                choices=[
                    ("intern", "Стажер"),
                    ("junior", "Junior"),
                    ("junior_plus", "Junior+"),
                    ("middle", "Middle"),
                    ("middle_plus", "Middle+"),
                    ("senior", "Senior"),
                    ("team_lead", "Team Lead"),
                ],
                default="junior",
                max_length=200,
                verbose_name="Уровень",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="status_vacancy",
            field=models.CharField(
                choices=[("open", " Открыта"), ("archived", "В архиве")],
                default="open",
                max_length=200,
                verbose_name="Статус вакансии",
            ),
        ),
    ]
