# Generated by Django 5.1 on 2024-11-22 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_company_count_employees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="stars",
            field=models.SmallIntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Оценка",
            ),
        ),
    ]
