# Generated by Django 5.1 on 2024-11-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_company_count_employees_alter_comment_stars_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="level",
            field=models.CharField(
                choices=[
                    ("none", "Не имеет значения"),
                    ("intern", "Стажер"),
                    ("junior", "Junior"),
                    ("junior_plus", "Junior+"),
                    ("middle", "Middle"),
                    ("middle_plus", "Middle+"),
                    ("senior", "Senior"),
                    ("team_lead", "Team Lead"),
                ],
                default="junior",
                max_length=200,
                verbose_name="Уровень",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="work_schedule",
            field=models.CharField(
                choices=[
                    ("full-time", "Полный рабочий день"),
                    ("part-time", "Частичная занятость"),
                    ("remote", "Удаленная работа"),
                    ("hybrid", "Гибридная работа"),
                ],
                default="full-time",
                max_length=200,
                verbose_name="График работы",
            ),
        ),
    ]
