# Generated by Django 5.1 on 2024-11-28 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_alter_vacancy_level_alter_vacancy_work_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacancies",
                to="companies.company",
                verbose_name="Компания",
            ),
        ),
    ]
