# Generated by Django 5.1 on 2024-11-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_alter_vacancy_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="city",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Город"
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="country",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Страна"
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="metro",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Станция метро"
            ),
        ),
    ]
