# Generated by Django 5.1 on 2024-11-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_vacancy_city_vacancy_country_vacancy_metro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="min_salary",
            field=models.SmallIntegerField(
                null=True, verbose_name="Минимальная зарплата"
            ),
        ),
    ]
