# Generated by Django 5.1 on 2024-11-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_vacancy_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="our_offers",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="Наши предложения"
            ),
        ),
    ]
