# Generated by Django 5.1 on 2024-11-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0010_vacancy_our_offers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="our_offers",
        ),
    ]
