# Generated by Django 5.1 on 2024-12-01 13:56

import common.service
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0011_remove_vacancy_our_offers"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "egrul",
                    models.FileField(
                        upload_to=common.service.get_path_for_check_company_egrul,
                        verbose_name="Выписка из ЕГРЮЛ и ЕГРИП",
                    ),
                ),
                (
                    "certificate",
                    models.FileField(
                        upload_to=common.service.get_path_for_check_company_certificate,
                        verbose_name="Cвидетельство о регистрации фирмы или ИП",
                    ),
                ),
                (
                    "certificate_nalog",
                    models.FileField(
                        upload_to=common.service.get_path_for_check_company_certificate_nalog,
                        verbose_name="Cправка о постановке на учет в налоговом органе",
                    ),
                ),
                (
                    "constitution",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=common.service.get_path_for_check_company_constitution,
                        verbose_name="Устав",
                    ),
                ),
                (
                    "license",
                    models.FileField(
                        upload_to=common.service.get_path_for_check_company_license,
                        verbose_name="Лицензия на необходимые виды деятельности",
                    ),
                ),
                (
                    "no_debt",
                    models.FileField(
                        upload_to=common.service.get_path_for_check_company_no_debt,
                        verbose_name="Справка, подтверждающая отсутствие налоговых задолженностей",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На расмотрении"),
                            ("accepted", "Принято"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        max_length=200,
                        verbose_name="Статус проверки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="companies.company",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проверка компании",
                "verbose_name_plural": "Проверки компании",
            },
        ),
    ]
