# Generated by Django 5.1 on 2024-12-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0012_checkcompany"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkcompany",
            name="consent",
            field=models.BooleanField(
                default=False, verbose_name="Согласие на обработку персональных данных"
            ),
        ),
    ]
