# Generated by Django 5.1 on 2024-12-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0016_alter_company_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkcompany",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Отправлено"),
                    ("pending", "На расмотрении"),
                    ("accepted", "Принято"),
                    ("rejected", "Отклонено"),
                ],
                default="pending",
                max_length=200,
                verbose_name="Статус проверки",
            ),
        ),
    ]
