# Generated by Django 5.1 on 2024-11-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsevacancy",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("accepted", "Приглашение"),
                    ("interview", "Интервью"),
                    ("offered", "Предложение на работу"),
                    ("rejected", "Отклонен"),
                ],
                default="new",
                max_length=200,
                verbose_name="Статус",
            ),
        ),
    ]
