# Generated by Django 5.1 on 2024-12-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responseletter",
            name="text",
            field=models.TextField(max_length=5000, verbose_name="Текст письма"),
        ),
    ]
