# Generated by Django 5.1 on 2024-11-24 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_subscription"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
