# Generated by Django 5.1 on 2024-11-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_alter_responsevacancy_status_interview"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="date_interview",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата интервью"
            ),
        ),
    ]
