# Generated by Django 5.1 on 2024-11-27 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0005_alter_messagetoresponse_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponseLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(max_length=1500, verbose_name="Текст письма"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "response_vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_letters",
                        to="chats.responsevacancy",
                        verbose_name="Отклик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сопроводительное письмо",
                "verbose_name_plural": "Сопроводительные письма",
            },
        ),
    ]
