# Generated by Django 5.1 on 2024-11-19 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("new_vacancy", "Новая вакансия"),
                            ("new_interview", "Новое интервью"),
                            ("new_message", "Новое сообщение"),
                            ("new_response", "Новый отклик"),
                            ("archive_vacancy", "Вакансия перенесена в архив"),
                        ],
                        max_length=255,
                    ),
                ),
                ("read", models.BooleanField(default=False, verbose_name="Прочитано")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление компании",
                "verbose_name_plural": "Уведомления компаний",
            },
        ),
        migrations.CreateModel(
            name="NotificationEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("new_vacancy", "Новая вакансия"),
                            ("new_interview", "Новое интервью"),
                            ("new_message", "Новое сообщение"),
                            ("new_response", "Новый отклик"),
                            ("archive_vacancy", "Вакансия перенесена в архив"),
                        ],
                        max_length=255,
                    ),
                ),
                ("read", models.BooleanField(default=False, verbose_name="Прочитано")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление работника",
                "verbose_name_plural": "Уведомления работников",
            },
        ),
    ]
