# Generated by Django 5.1 on 2024-11-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationcompany",
            name="type",
            field=models.CharField(
                choices=[
                    ("new_vacancy", "Новая вакансия"),
                    ("new_interview", "Новое интервью"),
                    ("new_message", "Новое сообщение"),
                    ("new_response", "Новый отклик"),
                    ("archive_vacancy", "Вакансия перенесена в архив"),
                    ("new_user", "На вас подписался новый пользователь"),
                    ("new_visitor", "Вашу страницу посетил новый пользователь"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="notificationemployee",
            name="type",
            field=models.CharField(
                choices=[
                    ("new_vacancy", "Новая вакансия"),
                    ("new_interview", "Новое интервью"),
                    ("new_message", "Новое сообщение"),
                    ("new_response", "Новый отклик"),
                    ("archive_vacancy", "Вакансия перенесена в архив"),
                    ("new_user", "На вас подписался новый пользователь"),
                    ("new_visitor", "Вашу страницу посетил новый пользователь"),
                ],
                max_length=255,
            ),
        ),
    ]
