# Generated by Django 5.1 on 2024-11-19 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_resume_experience_alter_resume_stacks"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationcompany",
            name="user",
        ),
        migrations.RemoveField(
            model_name="notificationemployee",
            name="user",
        ),
        migrations.AddField(
            model_name="notificationcompany",
            name="company",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notificationemployee",
            name="employee",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.employee",
            ),
            preserve_default=False,
        ),
    ]
